src/main/java/com/example/jeedemo/domain/Car.java
package com.example.jeedemo.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQuery;

@Entity
@NamedQuery(name = "car.unsold", query = "Select c from Car c where c.sold = false")
public class Car {
	
	private Long id;
	private String make;
	private String model;
	private Boolean sold = false;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getMake() {
		return make;
	}
	public void setMake(String make) {
		this.make = make;
	}
	public String getModel() {
		return model;
	}
	public void setModel(String model) {
		this.model = model;
	}
	public Boolean getSold() {
		return sold;
	}
	public void setSold(Boolean sold) {
		this.sold = sold;
	}
}

src/main/java/com/example/jeedemo/domain/Person.java
package com.example.jeedemo.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

@Entity
@NamedQueries({ 
	@NamedQuery(name = "person.all", query = "Select p from Person p")
})
public class Person {

	private Long id;

	private String firstName = "unknown";
	private String pin = "";
	private Date registrationDate = new Date();

	private List<Car> cars = new ArrayList<Car>();

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	@Size(min = 2, max = 20)
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Size(min = 2)
	public String getPin() {
		return pin;
	}
	public void setPin(String pin) {
		this.pin = pin;
	}

	@Temporal(TemporalType.DATE)
	public Date getRegistrationDate() {
		return registrationDate;
	}
	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	// Be careful here, both with lazy and eager fetch type
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	public List<Car> getCars() {
		return cars;
	}
	public void setCars(List<Car> cars) {
		this.cars = cars;
	}
}

src/main/java/com/example/jeedemo/web/PersonFormBean.java
package com.example.jeedemo.web;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.model.ListDataModel;
import javax.inject.Inject;
import javax.inject.Named;

import com.example.jeedemo.domain.Car;
import com.example.jeedemo.domain.Person;
import com.example.jeedemo.service.PersonManager;
import com.example.jeedemo.service.SellingManager;

@SessionScoped
@Named("personBean")
public class PersonFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Person person = new Person();
	private ListDataModel<Person> persons = new ListDataModel<Person>();
	
	private Person personToShow = new Person();
	private ListDataModel<Car> ownedCars = new ListDataModel<Car>();


	@Inject
	private PersonManager pm;
	
	@Inject
	private SellingManager sm;

	public Person getPerson() {
		return person;
	}
	public void setPerson(Person person) {
		this.person = person;
	}
	
	public ListDataModel<Person> getAllPersons() {
		persons.setWrappedData(pm.getAllPersons());
		return persons;
	}

	public ListDataModel<Car> getOwnedCars() {
		ownedCars.setWrappedData(pm.getOwnedCars(personToShow));
		return ownedCars;
	}
	
	// Actions
	public String addPerson() {
		pm.addPerson(person);
		return "showPersons";
		//return null;
	}

	public String deletePerson() {
		Person personToDelete = persons.getRowData();
		pm.deletePerson(personToDelete);
		return null;
	}
	
	public String showDetails() {
		personToShow = persons.getRowData();
		return "details";
	}
	
	public String disposeCar(){
		Car carToDispose = ownedCars.getRowData();
		sm.disposeCar(personToShow, carToDispose);
		return null;
	}
}

src/main/java/com/example/jeedemo/web/SaleFormBean.java
package com.example.jeedemo.web;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.example.jeedemo.domain.Car;
import com.example.jeedemo.domain.Person;
import com.example.jeedemo.service.PersonManager;
import com.example.jeedemo.service.SellingManager;

@SessionScoped
@Named("saleBean")
public class SaleFormBean implements Serializable {

	private static final long serialVersionUID = 1L;

	@Inject
	private SellingManager sm;

	@Inject
	private PersonManager pm;

	private Long carId;
	private Long personId;
	
	public Long getCarId() {
		return carId;
	}
	public void setCarId(Long carId) {
		this.carId = carId;
	}
	public Long getPersonId() {
		return personId;
	}
	public void setPersonId(Long personId) {
		this.personId = personId;
	}

	public List<Car> getAvailableCars() {
		return sm.getAvailableCars();
	}

	public List<Person> getAllPersons() {
		return pm.getAllPersons();
	}

	public String sellCar() {
		sm.sellCar(personId, carId);
		return null;
	}
}

src/main/webapp/add.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<ui:define name="content">
		<h:form id="personForm">
			<h:panelGrid columns="2">

				<h:outputText value="#{msg.personFirstNameLabel}" />
				<h:inputText id="firstName" value="#{personBean.person.firstName}"
					required="#{true}" />

				<h:outputText value="#{msg.personPinLabel}" />
				<h:inputText id="pin" value="#{personBean.person.pin}" />

				<h:outputText value="Registration date" />
				<rich:calendar value="#{personBean.person.registrationDate}"
					id="calendar" datePattern="dd.MM.yyyy" showApplyButton="#{true}"
					style="width:200px">
				</rich:calendar>
			</h:panelGrid>

			<h:commandButton value="#{msg.personFormOKButton}"
				action="#{personBean.addPerson}" />

			<h:panelGrid>
				<h:messages for="" />
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

		</h:form>

	</ui:define>
</ui:composition>

src/main/webapp/details.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">

	<ui:define name="content">
		<h:form>
			<h:dataTable value="#{personBean.ownedCars}" var="item">
				<f:facet name="header">Rented cars</f:facet>
				<h:column>
					<f:facet name="header">Make</f:facet>
					<h:outputText value="#{item.make}" />
				</h:column>

				<h:column>
					<f:facet name="header">Model</f:facet>
					<h:outputText value="#{item.model}" />
				</h:column>

				<h:column>
					<f:facet name="header">#{msg.action}</f:facet>
					<h:commandLink value="#{msg.actionDelete}"
						action="#{personBean.disposeCar}" />
				</h:column>

			</h:dataTable>
		</h:form>

	</ui:define>

</ui:composition>

src/main/webapp/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">
	<ui:define name="content">
		<p>#{msg.applicationInfo}</p>
	</ui:define>
</ui:composition>

src/main/webapp/index.jsp
<% response.sendRedirect("home.jsf"); %>

src/main/webapp/sell.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

	<ui:define name="content">
		<h:form id="personForm">
			<h:panelGrid columns="2">

				<h:outputText value=" Person " />
				<h:selectOneMenu value="#{saleBean.personId}">
					<f:selectItems value="#{saleBean.allPersons}" var="person"
						itemValue="#{person.id}" itemLabel="#{person.firstName}" />
				</h:selectOneMenu>

				<h:outputText value=" Car" />
				<h:selectOneMenu value="#{saleBean.carId}">
					<f:selectItems value="#{saleBean.availableCars}" var="car"
						itemValue="#{car.id}" itemLabel="#{car.make} #{car.model}" />
				</h:selectOneMenu>


			</h:panelGrid>

			<h:commandButton value="Sell" action="#{saleBean.sellCar}" />

			<h:panelGrid>
				<h:messages id="messages" showDetail="#{true}"
					showSummary="#{false}" />
			</h:panelGrid>

		</h:form>

	</ui:define>
</ui:composition>

src/main/webapp/showPersons.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	template="/templates/default.xhtml">

	<ui:define name="content">
		<h:form>
			<h:dataTable value="#{personBean.allPersons}" var="item">
				<f:facet name="header">#{msg.personAllLabel}</f:facet>
				<h:column>
					<f:facet name="header">#{msg.personFirstNameLabel}</f:facet>
					<h:outputText value="#{item.firstName}" />
				</h:column>

				<h:column>
					<f:facet name="header">#{msg.personPinLabel}</f:facet>
					<h:outputText value="#{item.pin}" />
				</h:column>

				<h:column>
					<f:facet name="header">#{msg.action}</f:facet>
					<h:commandLink value="#{msg.actionDelete}"
						action="#{personBean.deletePerson}" />
					<h:commandLink value=" Details " action="#{personBean.showDetails}"/>
				</h:column>

			</h:dataTable>
		</h:form>

	</ui:define>

</ui:composition>

src/main/webapp/templates/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><ui:insert name="windowTitle">#{msg.mainWindowTitle}</ui:insert>
	</title>
</h:head>
<h:body>
  <h:outputStylesheet library="css" name="default.css" target="body" />
	<div class="heading">
	  <ui:insert name="heading">
       #{msg.mainHeading}
     </ui:insert>
    </div>
	<div class="menuAndContent">
	 <div class="menu">
	   <ui:insert name="menu">
         <ui:include src="/views/main/menu.xhtml" />
       </ui:insert>
      </div>
	  <div class="content">
	     <ui:insert name="content" />
       </div>
	</div>
</h:body>
</html>

src/main/webapp/views/main/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
  <div>
	<h:form>
	  <ul>
		<li>
		  <h:commandLink action="home?faces-redirect=true">
			<h:outputText value="#{msg.linkHome}" />
		  </h:commandLink>
		</li>
		<li>
		  <h:commandLink action="add?faces-redirect=true">
			<h:outputText value="#{msg.personAddLabel}" />
		  </h:commandLink></li>
		<li>
		  <h:commandLink action="showPersons?faces-redirect=true">
			 <h:outputText value="#{msg.personAllLabel}" />
		  </h:commandLink>
		</li>
		<li>
		  <h:commandLink action="sell">
			 <h:outputText value=" Sell car" />
		  </h:commandLink>
		</li>
	</ul>
   </h:form>
  </div>
</ui:composition>